---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaas
    component: grafana
  name: grafana
  namespace: "openfaas"
spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: grafana
