---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaas
    component: grafana
  name: grafana-external
  namespace: "openfaas"
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 31113
  selector:
    app: grafana
