---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: "openfaas"
  labels:
    app: openfaas
    component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: grafana
        resources:
            requests:
              memory: 125Mi
        image: georgenicoll/faas-grafana:6.3.6
        imagePullPolicy: Always
        command:
          - "/etc/grafana/docker-entrypoint.sh"
        ports:
        - containerPort: 3000
          protocol: TCP